import type { PathStage } from '../../types/learning';

/** 16 Etappen — Variablen/Typen und Kontrollstrukturen getrennt (s02a/s02b). */
export const PATH_STAGES: PathStage[] = [
  {
    id: 's01',
    order: 1,
    title: 'Grundlagen informatischer Denkweise',
    subtitle: 'Problem, Algorithmus, Korrektheit',
    description: 'Einstieg: Was ist ein Problem, was ein Algorithmus, und wie liest man einfache Abläufe?',
    learningGoals: [
      'Problem, Algorithmus und Implementierung unterscheiden',
      'Einen Mini-Algorithmus in eigenen Worten erklären',
      'Einfache Traces am Beispiel durchspielen',
    ],
    prerequisiteStageIds: [],
    estimatedMinutes: 45,
    difficulty: 1,
    unitIds: ['s01-u01'],
  },
  {
    id: 's02a',
    order: 2,
    title: 'Datentypen und Variablen',
    subtitle: 'Zuweisung, Typen, Ausdrücke',
    description: 'Variablen, Zuweisungen und elementare Datentypen sicher lesen und schreiben.',
    learningGoals: [
      'Zuweisung und Ausdrücke formal nachvollziehen',
      'Ganzzahl vs. reell vs. Zeichenkette zuordnen',
      'Nebenwirkungen von Zuweisungen in Traces erkennen',
    ],
    prerequisiteStageIds: ['s01'],
    estimatedMinutes: 40,
    difficulty: 1,
    blockFocus: 'both',
    unitIds: ['s02a-u01'],
  },
  {
    id: 's02b',
    order: 3,
    title: 'Kontrollstrukturen',
    subtitle: 'Selektion und Schleifen',
    description: 'Wenn-dann-sonst, Zählschleifen und bedingte Wiederholungen strukturiert nutzen.',
    learningGoals: [
      'Selektion und Schleife in Pseudocode erkennen',
      'Schleifeninvariante grob beschreiben',
      'Abbruchbedingungen und typische Off-by-one-Fehler vermeiden',
    ],
    prerequisiteStageIds: ['s02a'],
    estimatedMinutes: 45,
    difficulty: 1,
    blockFocus: 'both',
    unitIds: ['s02b-u01'],
  },
  {
    id: 's03',
    order: 4,
    title: 'Algorithmen und Tracetabellen',
    subtitle: 'Ablauf mitverfolgen',
    description: 'Algorithmen Schritt für Schritt in Tabellenform ausführen und Zwischenstände dokumentieren.',
    learningGoals: [
      'Trace für gegebenen Algorithmus und Eingabe führen',
      'Variablenzustände pro Zeile festhalten',
      'Aus Trace Rückschlüsse auf Korrektheit ziehen',
    ],
    prerequisiteStageIds: ['s02b'],
    estimatedMinutes: 60,
    difficulty: 1,
    unitIds: ['s03-u01'],
  },
  {
    id: 's04',
    order: 5,
    title: 'Statische Reihungen',
    subtitle: 'Arrays, Index, Schleifen',
    description: 'Feste Länge, Indexbereich und typische Muster (Summe, Suche, Minimum).',
    learningGoals: [
      'Index und Länge einer Reihung sicher nutzen',
      'Einfache Array-Algorithmen in Pseudocode formulieren',
      'Grenzfälle (leer, ein Element) bedenken',
    ],
    prerequisiteStageIds: ['s03'],
    estimatedMinutes: 50,
    difficulty: 2,
    unitIds: ['s04-u01'],
  },
  {
    id: 's05',
    order: 6,
    title: 'Rekursion',
    prerequisiteStageIds: ['s04'],
    estimatedMinutes: 70,
    difficulty: 2,
    description: 'Basisfall, rekursiver Aufruf und Kette der Aufrufe verstehen.',
    learningGoals: ['Basisfall und Rekursionsschritt trennen', 'Kleine rekursive Programme per Hand ausführen'],
    unitIds: ['s05-u01'],
  },
  {
    id: 's06',
    order: 7,
    title: 'DynArray, Stack, Queue',
    prerequisiteStageIds: ['s05'],
    estimatedMinutes: 65,
    difficulty: 2,
    description: 'Dynamische Reihungen und abstrakte Datentypen Stack/Queue.',
    learningGoals: ['Push/Pop vs. enqueue/dequeue unterscheiden', 'LIFO und FIFO anwenden'],
    unitIds: ['s06-u01'],
  },
  {
    id: 's07',
    order: 8,
    title: 'OOP, Vererbung, Klassendiagramme',
    prerequisiteStageIds: ['s06'],
    estimatedMinutes: 80,
    difficulty: 2,
    description: 'Klassen, Objekte, Vererbung in offizieller Notation.',
    learningGoals: ['Klassendiagramm lesen und ergänzen', 'Kapselung und Vererbung erklären'],
    unitIds: ['s07-u01'],
  },
  {
    id: 's08',
    order: 9,
    title: 'Binärbaum, BST, Traversierungen',
    prerequisiteStageIds: ['s07'],
    estimatedMinutes: 75,
    difficulty: 2,
    description: 'BST-Eigenschaft und Pre/In/Post-Order.',
    learningGoals: ['Links kleiner, rechts größer anwenden', 'Traversierungen ausgeben'],
    unitIds: ['s08-u01'],
  },
  {
    id: 's09',
    order: 10,
    title: 'Kryptologie',
    prerequisiteStageIds: ['s08'],
    estimatedMinutes: 60,
    difficulty: 2,
    description: 'Grundbegriffe Vertraulichkeit, Integrität, Authentizität.',
    learningGoals: ['Symmetrisch vs. asymmetrisch grob einordnen', 'Hashing vs. Verschlüsselung'],
    unitIds: ['s09-u01'],
  },
  {
    id: 's10',
    order: 11,
    title: 'Codierung, Hamming, Huffman',
    prerequisiteStageIds: ['s09'],
    estimatedMinutes: 70,
    difficulty: 2,
    description: 'Fehlererkennung und baumbasierte Codierung.',
    learningGoals: ['Paritätsidee und Baumaufbau nachvollziehen'],
    unitIds: ['s10-u01'],
  },
  {
    id: 's11',
    order: 12,
    title: 'Datenbanken, ER, SQL',
    prerequisiteStageIds: ['s10'],
    estimatedMinutes: 80,
    difficulty: 2,
    description: 'ER-Modell, relationales Schema, grundlegende SQL-Klauseln.',
    learningGoals: ['SELECT mit JOIN und WHERE formulieren', 'GROUP BY vs. WHERE unterscheiden'],
    unitIds: ['s11-u01'],
  },
  {
    id: 's12',
    order: 13,
    title: 'Automaten, Mealy, Kellerautomat',
    prerequisiteStageIds: ['s11'],
    estimatedMinutes: 75,
    difficulty: 3,
    description: 'Endliche Automaten, ausgabebehaftete Übergänge, Keller.',
    learningGoals: ['Zustand und Eingabe lesen', 'PDA-Grundidee'],
    unitIds: ['s12-u01'],
  },
  {
    id: 's13',
    order: 14,
    title: 'Formale Sprachen und Grammatiken',
    prerequisiteStageIds: ['s12'],
    estimatedMinutes: 65,
    difficulty: 3,
    description: 'Chomsky, Ableitungen, Typ-3-Sprachen.',
    learningGoals: ['Ableitung Schritt für Schritt führen'],
    unitIds: ['s13-u01'],
  },
  {
    id: 's14',
    order: 15,
    title: 'Netzwerke, Datenschutz, Chancen und Risiken',
    prerequisiteStageIds: ['s13'],
    estimatedMinutes: 55,
    difficulty: 2,
    description: 'Grundlagen Vernetzung und gesellschaftliche Aspekte.',
    learningGoals: ['Schichtenmodell grob benennen', 'Datenschutzbegriffe zuordnen'],
    unitIds: ['s14-u01'],
  },
  {
    id: 's15',
    order: 16,
    title: 'Klausurstrategie und Zeitmanagement',
    prerequisiteStageIds: ['s14'],
    estimatedMinutes: 40,
    difficulty: 1,
    description: 'Strukturiert arbeiten, Punkte einteilen — nach fachlicher Basis.',
    learningGoals: ['Bearbeitungsreihenfolge planen', 'Teilpunkte sichern'],
    blockFocus: 'both',
    unitIds: ['s15-u01'],
  },
];
