import type { GlossaryEntry } from '../types/learning';

export const GLOSSARY: GlossaryEntry[] = [
  {
    id: 'algorithmus',
    term: 'Algorithmus',
    shortDef: 'Endliche, eindeutige Schrittfolge zur Problemlösung.',
    simpleExplanation:
      'Wie ein Rezept: Jeder Schritt ist klar, und wenn du alles befolgst, weißt du genau, was als Nächstes dran ist.',
    formalDefinition:
      'Eine endliche Folge elementarer, eindeutig ausführbarer Anweisungen, die bei zulässiger Eingabe nach endlich vielen Schritten stoppt und eine Ausgabe liefert.',
    miniExample: '„Solange n > 0: n ← n−1“ mit Start n=2 stoppt nach zwei Durchläufen.',
    relatedUnitIds: ['s01-u01'],
    relatedTermIds: ['problem', 'implementierung'],
    officialRef: 'KC Informatik 2017 — algorithmisches Grundverständnis',
  },
  {
    id: 'problem',
    term: 'Problem (informatisch)',
    shortDef: 'Aufgabe mit Eingabe, gewünschter Ausgabe und ggf. Vorbedingungen.',
    simpleExplanation:
      'Du bekommst etwas gegeben (Eingabe) und sollst etwas Bestimmtes herausfinden oder erzeugen (Ausgabe).',
    formalDefinition: 'Tripel aus Eingabemenge, Ausgabemenge und der gesuchten Beziehung/Funktion dazwischen.',
    miniExample: '„Sortiere die Liste“: Eingabe Liste, Ausgabe sortierte Liste.',
    relatedUnitIds: ['s01-u01'],
    relatedTermIds: ['algorithmus'],
  },
  {
    id: 'implementierung',
    term: 'Implementierung',
    shortDef: 'Umsetzung eines Algorithmus in einer konkreten Notation oder Sprache.',
    simpleExplanation:
      'Der Algorithmus ist die Idee; die Implementierung schreibt sie so auf, dass ein Computer (oder die Prüfung) sie nachvollziehen kann.',
    formalDefinition: 'Konkrete Darstellung eines Algorithmus in Pseudocode, Struktogramm oder Programmiersprache gemäß Vorgaben.',
    miniExample: 'Derselbe Suchalgorithmus einmal als Struktogramm, einmal als Pseudocode.',
    relatedUnitIds: ['s01-u01'],
    relatedTermIds: ['algorithmus'],
    officialRef: 'Ergänzende Hinweise 2021 — Pseudocode/Notation',
  },
  {
    id: 'variable',
    term: 'Variable',
    shortDef: 'Benannter Speicherplatz für einen Wert.',
    simpleExplanation: 'Wie ein beschriftetes Fach: du legst einen Wert ab und holst ihn später wieder.',
    formalDefinition: 'Ein Bezeichner, der zur Laufzeit (bzw. im Trace) auf einen gespeicherten Wert eines bestimmten Typs verweist.',
    miniExample: 'x ← 7 speichert 7 unter dem Namen x.',
    relatedUnitIds: ['s02a-u01'],
    relatedTermIds: ['zuweisung', 'datentyp'],
    commonConfusions: [{ withTermId: 'ausdruck', note: 'Variable ist der Speicherort; Ausdruck wird ausgewertet.' }],
  },
  {
    id: 'zuweisung',
    term: 'Zuweisung',
    shortDef: 'Speichert den Wert eines Ausdrucks in einer Variable (z. B. x ← ausdruck).',
    simpleExplanation: 'Zuerst rechts ausrechnen, dann in die Variable links schreiben — der alte Wert ist weg.',
    formalDefinition: 'Anweisung der Form Ziel ← Quelle; die Quelle wird ausgewertet, das Ergebnis ersetzt den Wert des Ziels.',
    miniExample: 'a ← 2; a ← a + 1 → a ist 3.',
    relatedUnitIds: ['s02a-u01'],
    relatedTermIds: ['variable', 'ausdruck'],
  },
  {
    id: 'datentyp',
    term: 'Datentyp',
    shortDef: 'Art des Werts (z. B. Ganzzahl, reell, Zeichenkette).',
    simpleExplanation: 'Legt fest, welche Werte erlaubt sind und welche Operationen Sinn ergeben.',
    formalDefinition: 'Klassifikation von Werten und den darauf erlaubten Operationen; verhindert unsinnige Kombinationen.',
    miniExample: '3.14 eher reell; „Hallo“ ist Zeichenkette.',
    relatedUnitIds: ['s02a-u01'],
    relatedTermIds: ['variable'],
  },
  {
    id: 'ausdruck',
    term: 'Ausdruck',
    shortDef: 'Etwas, das zu einem Wert ausgewertet wird.',
    simpleExplanation: 'Rechnung oder Kombination aus Werten und Variablen, z. B. 2 + x * 3.',
    formalDefinition: 'Syntaktisch korrekte Kombination aus Literalen, Variablen, Operatoren und Klammern mit definiertem Auswertungswert.',
    miniExample: 'Mit Punkt-vor-Strich: 2 + 3 * 4 = 14.',
    relatedUnitIds: ['s02a-u01'],
    relatedTermIds: ['zuweisung'],
  },
  {
    id: 'selektion',
    term: 'Selektion',
    shortDef: 'Verzweigung: je nach Bedingung unterschiedliche Anweisungen.',
    simpleExplanation: 'Wenn-dann-sonst: nur ein Zweig wird ausgeführt.',
    formalDefinition: 'Kontrollstruktur, die abhängig von einem booleschen Wert zwischen Alternativen wählt.',
    miniExample: 'wenn x < 0 dann x ← −x.',
    relatedUnitIds: ['s02b-u01'],
    relatedTermIds: ['schleife', 'bedingung'],
  },
  {
    id: 'schleife',
    term: 'Schleife',
    shortDef: 'Wiederholt einen Block, solange eine Bedingung gilt oder bis Zähler fertig.',
    simpleExplanation: 'Damit musst du Code nicht dutzendfach abschreiben.',
    formalDefinition: 'Iterative Kontrollstruktur mit Eintritts-/Austrittsbedingung und Rumpf.',
    miniExample: 'für i von 1 bis n: summe ← summe + a[i].',
    relatedUnitIds: ['s02b-u01', 's04-u01'],
    relatedTermIds: ['bedingung', 'trace'],
    commonConfusions: [{ withTermId: 'selektion', note: 'Schleife wiederholt; Selektion wählt einmalig.' }],
  },
  {
    id: 'bedingung',
    term: 'Bedingung',
    shortDef: 'Wahrheitswert (wahr/falsch), oft aus Vergleichen.',
    simpleExplanation: 'Steuert if und while: erst auswerten, dann entscheiden.',
    formalDefinition: 'Boolescher Ausdruck, der die Ausführung von Selektion oder Schleife steuert.',
    miniExample: 'i ≤ n, x ≠ 0.',
    relatedUnitIds: ['s02b-u01'],
    relatedTermIds: ['selektion', 'schleife'],
  },
  {
    id: 'trace',
    term: 'Tracetabelle',
    shortDef: 'Tabelle, die Variablenzustände Schritt für Schritt protokolliert.',
    simpleExplanation: 'Wie Film-Frames: jede Zeile = kurzer Fortschritt im Algorithmus.',
    formalDefinition: 'Systematische Dokumentation der Zustände aller relevanter Variablen über die Ausführungssequenz.',
    miniExample: 'Spalten für i, s; Zeilen pro Schleifendurchlauf.',
    relatedUnitIds: ['s03-u01'],
    relatedTermIds: ['algorithmus', 'variable'],
  },
  {
    id: 'reihung',
    term: 'Reihung (Array)',
    shortDef: 'Feste Anzahl gleichartiger Elemente mit Indexzugriff.',
    simpleExplanation: 'Nummerierte Liste: jedes Element hat eine Position.',
    formalDefinition: 'Statische Datenstruktur A[untere..obere Grenze] mit direktem Zugriff über Index.',
    miniExample: 'A[1..4] hat vier Plätze.',
    relatedUnitIds: ['s04-u01'],
    relatedTermIds: ['index', 'schleife'],
  },
  {
    id: 'index',
    term: 'Index',
    shortDef: 'Positionsangabe eines Elements in einer Reihung.',
    simpleExplanation: 'Achtung: manchmal 1-basiert, manchmal 0 — Aufgabe genau lesen.',
    formalDefinition: 'Ganzzahliger Selektor in den gültigen Grenzen der Reihung.',
    miniExample: 'Bei A[1..n] sind 1 und n gültig, n+1 meist nicht.',
    relatedUnitIds: ['s04-u01'],
    relatedTermIds: ['reihung'],
    commonConfusions: [{ withTermId: 'reihung', note: 'Index ist Position; Länge ist Anzahl Elemente.' }],
  },
  {
    id: 'rekursion',
    term: 'Rekursion',
    shortDef: 'Funktion/Algorithmus ruft sich selbst auf — mit Basisfall.',
    simpleExplanation: 'Teile das Problem in kleinere gleichartige Teile, bis der Basisfall trivial ist.',
    formalDefinition: 'Technik, bei der die Lösung durch Selbstaufruf mit Parameter näher am Basisfall definiert wird.',
    miniExample: 'fak(n) = 1 wenn n=0, sonst n * fak(n−1).',
    relatedUnitIds: ['s05-u01'],
    relatedTermIds: ['algorithmus'],
  },
  {
    id: 'stack',
    term: 'Stack',
    shortDef: 'LIFO: zuletzt rein, zuerst raus.',
    simpleExplanation: 'Wie Stapel Teller: nur oben drauflegen und wegnehmen.',
    formalDefinition: 'Abstrakter Datentyp mit push/pop auf einer Seite; Last-In-First-Out.',
    miniExample: 'push(1), push(2), pop → 2.',
    relatedUnitIds: ['s06-u01'],
    relatedTermIds: ['queue'],
    commonConfusions: [{ withTermId: 'queue', note: 'Stack LIFO; Queue FIFO.' }],
  },
  {
    id: 'queue',
    term: 'Queue',
    shortDef: 'FIFO: zuerst rein, zuerst raus.',
    simpleExplanation: 'Warteschlange an der Kasse.',
    formalDefinition: 'Abstrakter Datentyp mit enqueue am Ende und dequeue am Anfang.',
    miniExample: 'enqueue(a), enqueue(b), dequeue → a.',
    relatedUnitIds: ['s06-u01'],
    relatedTermIds: ['stack'],
  },
  {
    id: 'bst',
    term: 'Binärer Suchbaum (BST)',
    shortDef: 'Binärbaum mit Ordnung: links kleiner, rechts größer als Wurzel.',
    simpleExplanation: 'Suchbaum-Eigenschaft für jeden Knoten rekursiv.',
    formalDefinition: 'Binärbaum, bei dem für jeden Knoten alle Werte im linken Teilbaum kleiner und im rechten größer sind.',
    miniExample: 'Einfügen durch Vergleich mit Wurzel und Abstieg.',
    relatedUnitIds: ['s08-u01'],
    relatedTermIds: ['algorithmus'],
  },
  {
    id: 'sql_select',
    term: 'SELECT (SQL)',
    shortDef: 'Projiziert Spalten und liefert eine Ergebnisrelation.',
    simpleExplanation: 'Welche Spalten willst du sehen — kombiniert mit FROM/JOIN/WHERE.',
    formalDefinition: 'Kern der deklarativen Abfrage; wird mit weiteren Klauseln ausgewertet.',
    miniExample: 'SELECT Name FROM Kunde WHERE Ort = \'Hannover\'.',
    relatedUnitIds: ['s11-u01'],
    relatedTermIds: ['join', 'having_where'],
  },
  {
    id: 'join',
    term: 'JOIN',
    shortDef: 'Kombiniert Zeilen zweier (oder mehr) Tabellen nach Bedingung.',
    simpleExplanation: 'Verbindet passende Datensätze — z. B. über Fremdschlüssel.',
    formalDefinition: 'Relationale Operation, die kartesisches Produkt einschränkt durch Join-Bedingung.',
    miniExample: 'FROM Bestellung JOIN Kunde ON Bestellung.KNr = Kunde.KNr.',
    relatedUnitIds: ['s11-u01'],
    relatedTermIds: ['sql_select'],
  },
  {
    id: 'having_where',
    term: 'WHERE vs. HAVING',
    shortDef: 'WHERE filtert Zeilen vor Gruppierung; HAVING filtert Gruppen danach.',
    simpleExplanation: 'Erst Zeilen auswählen, gruppieren, dann Gruppen einschränken.',
    formalDefinition: 'Prädikat in WHERE wirkt auf einzelne Zeilen; HAVING auf Gruppenergebnisse nach GROUP BY.',
    miniExample: 'WHERE Alter > 18; HAVING COUNT(*) > 5 nach GROUP BY Ort.',
    relatedUnitIds: ['s11-u01'],
    relatedTermIds: ['sql_select'],
  },
  {
    id: 'dea',
    term: 'DEA',
    shortDef: 'Deterministischer endlicher Automat: pro Zustand und Eingabe genau ein Übergang.',
    simpleExplanation: 'Endliche Zustände, Eingabe gelesen, Pfeile sind eindeutig.',
    formalDefinition: '5-Tupel (Z, Σ, δ, z₀, F) mit δ : Z × Σ → Z.',
    miniExample: 'Erkennen von Mustern über endliches Alphabet.',
    relatedUnitIds: ['s12-u01'],
    relatedTermIds: ['mealy'],
  },
  {
    id: 'mealy',
    term: 'Mealy-Automat',
    shortDef: 'Ausgabe hängt von Zustand und Eingabezeichen (am Übergang).',
    simpleExplanation: 'Anders als Moore oft: Ausgabe steht am Pfeil, nicht nur im Zustand.',
    formalDefinition: 'Endlicher Automat mit Ausgabefunktion λ : Z × Σ → Γ am Übergang.',
    miniExample: 'Eingabe 1 unter Ausgabe y beim Wechsel A→B.',
    relatedUnitIds: ['s12-u01'],
    relatedTermIds: ['dea'],
    commonConfusions: [{ withTermId: 'dea', note: 'DEA ohne Ausgabe; Mealy erweitert um Ausgaben an Übergängen.' }],
  },
  {
    id: 'grammatik',
    term: 'Grammatik (formal)',
    shortDef: 'Regeln, die eine formale Sprache erzeugen.',
    simpleExplanation: 'Startsymbol, Nichtterminale, Produktionen — Ableitung Schritt für Schritt.',
    formalDefinition: 'Vier-Tupel (N, T, P, S) nach Chomsky-Hierarchie klassifizierbar.',
    miniExample: 'S → aS | b erzeugt Wörter mit a’s und abschließend b.',
    relatedUnitIds: ['s13-u01'],
    relatedTermIds: ['algorithmus'],
  },
  {
    id: 'hashing',
    term: 'Hashfunktion',
    shortDef: 'Abbildung großer Daten auf feste kurze Prüfsumme.',
    simpleExplanation: 'Integrität prüfen: kleine Änderung → anderer Hash.',
    formalDefinition: 'Funktion H mit Kollisionswahrscheinlichkeit; kryptografisch stark vs. schwach unterschieden.',
    miniExample: 'Prüfsumme einer Datei vergleichen.',
    relatedUnitIds: ['s09-u01'],
    relatedTermIds: ['algorithmus'],
  },
  {
    id: 'verschluesselung',
    term: 'Verschlüsselung',
    shortDef: 'Umwandlung von Klartext in Geheimtext mit Schlüssel.',
    simpleExplanation: 'Symmetrisch: ein Schlüssel; asymmetrisch: Schlüsselpaar.',
    formalDefinition: 'Algorithmus + Schlüsselraum; Ziel u. a. Vertraulichkeit.',
    miniExample: 'AES symmetrisch; RSA asymmetrisch (Grundidee).',
    relatedUnitIds: ['s09-u01'],
    relatedTermIds: ['hashing'],
  },
  {
    id: 'huffman',
    term: 'Huffman-Codierung',
    shortDef: 'Präfixfreier Code aus Häufigkeiten — optimal unter bestimmten Voraussetzungen.',
    simpleExplanation: 'Seltene Zeichen längere Codes, häufige kürzere.',
    formalDefinition: 'Greedy-Aufbau eines binären Baumes aus den kleinsten Teilbäumen.',
    miniExample: 'Zwei seltenste Symbole zuerst zusammenfassen.',
    relatedUnitIds: ['s10-u01'],
    relatedTermIds: ['algorithmus'],
  },
  {
    id: 'hamming',
    term: 'Hamming-Code',
    shortDef: 'Linearer Fehlerkorrektur-/Erkennungscode (hier oft (7,4)).',
    simpleExplanation: 'Paritätsbits an festen Positionen — Syndrom zeigt Fehlerbit.',
    formalDefinition: 'Codierung mit Hamming-Distanz > 1 erlaubt Erkennung/Korrektur einzelner Bitfehler.',
    miniExample: 'Layout p0 p1 d0 p2 d1 d2 d3 nach Anlage.',
    relatedUnitIds: ['s10-u01'],
    relatedTermIds: ['algorithmus'],
  },
  {
    id: 'netzwerk',
    term: 'Paket / Schichtenmodell',
    shortDef: 'Daten werden in Schichten mit Headern gekapselt (Didaktik).',
    simpleExplanation: 'Jede Schicht spricht mit der Gegenstelle auf gleicher Schicht.',
    formalDefinition: 'Referenzmodelle (z. B. TCP/IP, OSI) strukturieren Protokolle.',
    miniExample: 'HTTP auf TCP auf IP auf Ethernet.',
    relatedUnitIds: ['s14-u01'],
    relatedTermIds: [],
  },
  {
    id: 'datenschutz',
    term: 'Datenschutz',
    shortDef: 'Schutz personenbezogener Daten vor Missbrauch.',
    simpleExplanation: 'Zweckbindung, Datenminimierung, Rechte der Betroffenen (Grundideen).',
    formalDefinition: 'Rechtlicher und technischer Rahmen (z. B. DSGVO-Prinzipien in Unterrichtskontext).',
    miniExample: 'Einwilligung für Nutzung von Kontaktdaten.',
    relatedUnitIds: ['s14-u01'],
    relatedTermIds: [],
  },
];

export const GLOSSARY_BY_ID: Record<string, GlossaryEntry> = Object.fromEntries(
  GLOSSARY.map((g) => [g.id, g])
);
